### ISSUE TITLE
Messed up

### ISSUE THREAD

**Issue by AGCOM** [alibaba/UltraViewPager#48]
#35 #32 
This is the error =
```
08-27 13:54:30.003 11262-11262/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: ir.agcom.mylitener, PID: 11262
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'int com.tmall.ultraviewpager.UltraViewPagerAdapter.getCount()' on a null object reference
                                                       at com.tmall.ultraviewpager.UltraViewPagerView.getCurrentItem(UltraViewPagerView.java:217)
                                                       at com.tmall.ultraviewpager.UltraViewPagerView.onMeasurePage(UltraViewPagerView.java:86)
                                                       at com.tmall.ultraviewpager.UltraViewPagerView.onMeasure(UltraViewPagerView.java:82)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:727)
                                                       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:463)
                                                       at com.tmall.ultraviewpager.UltraViewPager.onMeasure(UltraViewPager.java:179)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1028)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
                                                       at android.view.View.measure(View.java:17547)
                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```
and this is my layout = 
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.tmall.ultraviewpager.UltraViewPager android:id="@+id/top_pager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        app:upv_scrollmode="horizontal"
        app:upv_multiscreen="true"/>

    <com.tmall.ultraviewpager.UltraViewPager android:id="@+id/bottom_pager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1"
        app:upv_scrollmode="horizontal"
        app:upv_multiscreen="true"/>

</LinearLayout>
```
This happens when i try to inflate this layout.
Also, Error is shown in android studio layout preview.
Using library version 1.0.6

**Comment by AGCOM** [comment]
AnyBody?

**Comment by AGCOM** [comment]
Alive?

**Comment by MikeAfc** [comment]
Seems not set adapter when new a UltraViewPager, but i fixed this in 1.0.6, suggest set a breakpoint with debug.

com.tmall.ultraviewpager.UltraViewPagerView#getCurrentItem:

`@Override
    public int getCurrentItem() {
        if (pagerAdapter != null && pagerAdapter.getCount() != 0) {
            int position = super.getCurrentItem();
            return position % pagerAdapter.getRealCount();
        }
        return super.getCurrentItem();
    }`

**Comment by Yeaji-Lim** [comment]
i use 1.0.6.1 library!! but it isn't fixed getcurrentitem!! it's same as before...

**Comment by longerian** [comment]
ok 1.0.6.4 has fixed it. 
The recommend way to avoid it is set an adapter to UltraViewPager when init it.
